# Facing trouble in installing tensor flow

## use
### pip install --upgrade tensorflow==2.0.0-rc1

In [1]:
import tensorflow as tf

In [2]:
a=tf.constant(10)

In [3]:
b=tf.constant(20)

In [4]:
a+b

<tf.Tensor: id=2, shape=(), dtype=int32, numpy=30>

In [5]:
print(a+b)

tf.Tensor(30, shape=(), dtype=int32)


In [6]:
c=a+b

In [7]:
tf.executing_eagerly()

True

In [8]:
c.numpy()

30

In [9]:
type(c.numpy())

numpy.int32

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [11]:
# hide warnings
import warnings
warnings.filterwarnings('ignore')

In [12]:
tf.__version__

'2.0.0-rc1'

In [13]:
p=tf.constant(10)

In [14]:
#p.assign(20)

In [15]:
q=tf.Variable(10)

In [16]:
q.assign(20)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=20>

In [17]:
from datetime import datetime
import os
import pathlib

t=datetime.utcnow().strftime("%Y%m%d%H%M%S")
log_dir="tf_logs"
logd="{}/r{}/".format(log_dir,t)


from pathlib import Path
home=str(Path.home())

logdir = os.path.join(os.sep,home,logd)

if not os.path.exists(logdir):
    os.makedirs(logdir)

In [18]:
logdir

'C:\\Users\\Riya Gaur\\tf_logs/r20200721151039/'

In [19]:
a

<tf.Tensor: id=0, shape=(), dtype=int32, numpy=10>

In [20]:
b

<tf.Tensor: id=1, shape=(), dtype=int32, numpy=20>

In [21]:
tf.multiply(a,b).numpy()

200

In [22]:
a_matrix=tf.constant([[1,2],[3,4]])
b_matrix=tf.constant([[5,6],[7,8]])
b_matrix

<tf.Tensor: id=18, shape=(2, 2), dtype=int32, numpy=
array([[5, 6],
       [7, 8]])>

In [23]:
tf.matmul(a_matrix,b_matrix)

<tf.Tensor: id=19, shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [24]:
print(a_matrix, b_matrix , sep="\n")

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


In [25]:
var=tf.Variable(3.)

In [26]:
var

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [27]:
var.numpy()

3.0

In [28]:
d=tf.Variable(np.random.randn(3,3))

In [29]:
d

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float64, numpy=
array([[-1.10182405,  1.18189843,  0.0407831 ],
       [-0.0938427 , -0.78163417, -0.58631028],
       [ 1.73904405, -0.03070333,  0.16362623]])>

In [30]:
d

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float64, numpy=
array([[-1.10182405,  1.18189843,  0.0407831 ],
       [-0.0938427 , -0.78163417, -0.58631028],
       [ 1.73904405, -0.03070333,  0.16362623]])>

In [31]:
var.assign_add(10)
print(var)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=13.0>


In [32]:
var.assign_sub(1)
print(var)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=12.0>


In [33]:
v=tf.Variable([[3.,3.2],[1.2,2.2]])
print('name   :',v.name)
print('type   :',v.dtype)
print('shape  :',v.shape)
print('device :',v.device)

name   : Variable:0
type   : <dtype: 'float32'>
shape  : (2, 2)
device : /job:localhost/replica:0/task:0/device:CPU:0


In [34]:
@tf.function
def func(a,b):
    with tf.name_scope('first'):
        z=tf.multiply(a,b,name='z')
    with tf.name_scope('second'):
        y1=tf.constant(3,name='3')
        y2=tf.constant(4)
        w1=tf.add(z,y1,name='w1')
        w2=tf.add(z,y2,name='w2')
    return(w1+w2)

In [35]:
import warnings
warnings.filterwarnings('ignore')
func(10,20)

<tf.Tensor: id=61, shape=(), dtype=int32, numpy=407>

In [39]:
@tf.function
def g(x):
    y=tf.reduce_sum(x)
    if y>0:
        return y
    return tf.abs(y)

In [40]:
w= tf.Variable(3.0)

with tf.GradientTape() as tape:
    expression = tf.exp(w) + 2 * w + w * w
    
grad = tape.gradient(expression,w)
print(f'The gradient of exp at {w.numpy()} is {grad.numpy()}')

The gradient of exp at 3.0 is 28.08553695678711


In [41]:
def sigmoid(x):
    return 1/(1 + tf.exp(-x))

In [42]:
x = tf.Variable(0.)

with tf.GradientTape() as tape:
    sig = sigmoid(x)
    
res = tape.gradient(sig, x).numpy()
print('The gradient of the sigmoid function at 0.0 is ', res)

The gradient of the sigmoid function at 0.0 is  0.25
